### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Roshi617** [Dan3436/gddownloader#1]
I tried using this with an audio ID higher than 469775 but it didn't work, specifically ID 473947. I put in the name of the song according to GD and this ID and it couldn't find it.

I even went to Wayback Machine [https://web.archive.org/web/20160730131249/https://www.newgrounds.com/audio/listen/473947](https://web.archive.org/web/20160730131249/https://www.newgrounds.com/audio/listen/473947), no luck unfortunately.

So does this tool or method even work anymore?

**Comment by d4n3436** [comment]
The method stopped working some time ago. The server is returning an error 404 so it probably means that the songs got actually deleted.
